version: '3.9'

services:
  # Redis
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - weather_wise_travel

networks:
  weather_wise_travel:
    driver: bridge
